export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const GET_BC_DATA = "GET_BC_DATA";
export const GET_BUYER_RECORDS = "GET_BUYER_RECORDS";
export const GET_STATUS = "GET_STATUS";
